name: Node.js Package

on:
  push:
    branches:
      - main
      - main-old-design

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@CG-squad'

      - name: Setup GIT
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          default: patch
          patch-wording: 'patch,fixes'
          rc-wording: 'preview'
          preid: 'preview'
          skip-tag:  'true'

      - name: Build & Publish
        run: |
          npm install
          npm run-script build
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
